[package]
name = "uphf-ics"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "lib/*"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["cookies"] }
scraper = "0.20"

[dependencies]
tokio = { workspace = true }
scraper = { workspace = true }
uphf-auth = { path = "lib/uphf-auth" }
config = { path = "lib/config" }
