services:
  uphf-ics:
    image: galacs/uphf-ics
    build: ../
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uphf-ics.rule=Host(`uphf-ics.dev.ait-younes.fr`)"
      - "traefik.http.routers.uphf-ics.entrypoints=web"
      - "traefik.http.services.uphf-ics.loadbalancer.server.port=8080"

      - traefik.http.routers.uphf-ics.middlewares=http-cache
      - traefik.http.middlewares.http-cache.plugin.souin.api.souin
      - traefik.http.middlewares.http-cache.plugin.souin.default_cache.ttl=200s
      - traefik.http.middlewares.http-cache.plugin.souin.default_cache.allowed_http_verbs=GET
      # - traefik.http.middlewares.http-cache.plugin.souin.log_level=debug
      #- traefik.http.middlewares.http-cache.plugin.souin.default_cache.default_cache.key.hash=true
      - traefik.http.middlewares.http-cache.plugin.souin.default_cache.key.headers=Authorization

  reverse-proxy:
    image: traefik:v3.1
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --experimental.plugins.souin.modulename=github.com/darkweak/souin
      - --experimental.plugins.souin.version=v1.7.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
